# Generated by Django 2.2 on 2019-04-30 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('sick', 'sick'), ('business', 'business')], default='sick', max_length=10)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approve_status', models.CharField(choices=[('pending', 'pending'), ('disapprove', 'disapprove'), ('approve', 'approve')], default='pending', max_length=10)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
